version: "3"

services:
  servicecenter:
    image: servicecomb/service-center
    ports:
      - "30100:30100"
    hostname: servicecenter
  mysql:
    build:
      context: ../database
      dockerfile: ../docker/mysql.dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    hostname: mysql
  customer-manage:
    depends_on:
      - mysql
      - servicecenter
    build:
      context: .
      dockerfile: customer-manage.dockerfile
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100
      spring_datasource_url: jdbc:mysql://mysql:3306/customer?characterEncoding=utf8&useSSL=false
#  edge-service:
#    depends_on:
#      - mysql
#      - servicecenter
#    build:
#      context: .
#      dockerfile: edge-service.dockerfile
#    environment:
#      servicecomb_service_registry_address: http://servicecenter:30100
  gateway:
    depends_on:
      - mysql
      - servicecenter
    build:
      context: .
      dockerfile: gateway.dockerfile
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100
    ports:
      - "8889:8889"
  house-order:
    depends_on:
      - mysql
      - servicecenter
    build:
      context: .
      dockerfile: house-order.dockerfile
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100
      spring_datasource_url: jdbc:mysql://mysql:3306/house_order?characterEncoding=utf8&useSSL=false
  login:
    depends_on:
      - mysql
      - servicecenter
    build:
      context: .
      dockerfile: login.dockerfile
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100
      spring_datasource_url: jdbc:mysql://mysql:3306/login?characterEncoding=utf8&useSSL=false
  realestate:
    depends_on:
      - mysql
      - servicecenter
    build:
      context: .
      dockerfile: realestate.dockerfile
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100
      spring_datasource_url: jdbc:mysql://mysql:3306/realestate?characterEncoding=utf8&useSSL=false
  user-center:
    depends_on:
      - mysql
      - servicecenter
    build:
      context: .
      dockerfile: user-center.dockerfile
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100



