version: "3"

services:
  servicecenter:
    image: servicecomb/service-center
    hostname: servicecenter
    ports:
      - "30100:30100"
  mysql:
    image: 192.168.88.244:5000/servicecomb-samples/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    hostname: mysql
  customer-manage:
    image: 192.168.88.244:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/customer-manage
    command: ["192.168.88.244:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    environment:
      servicecomb_service_registry_address: http://192.168.88.244:30100
      spring_datasource_url: jdbc:mysql://192.168.88.244:3306/customer?characterEncoding=utf8&useSSL=false
    ports:
      - "7779:7779"
  edge-service:
    image: 192.168.88.244:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/edge-service
    command: ["192.168.88.244:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    environment:
      servicecomb_service_registry_address: http://192.168.88.244:30100
    ports:
      - "9090:9090"
#  gateway:
#    depends_on:
#      - servicecenter
#    build:
#      context: .
#      dockerfile: gateway.dockerfile
#    environment:
#      servicecomb_service_registry_address: http://192.168.88.244:30100
#    ports:
#      - "8889:8889"
  house-order:
    image: 192.168.88.244:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/house-order
    command: ["192.168.88.244:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    environment:
      servicecomb_service_registry_address: http://192.168.88.244:30100
      spring_datasource_url: jdbc:mysql://192.168.88.244:3306/house_order?characterEncoding=utf8&useSSL=false
    ports:
      - "6788:6788"
  login:
    image: 192.168.88.244:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/login
    command: ["192.168.88.244:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    environment:
      servicecomb_service_registry_address: http://192.168.88.244:30100
      spring_datasource_url: jdbc:mysql://192.168.88.244:3306/login?characterEncoding=utf8&useSSL=false
    ports:
      - "6777:6777"
  realestate:
    image: 192.168.88.244:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/realestate
    command: ["192.168.88.244:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    environment:
      servicecomb_service_registry_address: http://192.168.88.244:30100
      spring_datasource_url: jdbc:mysql://192.168.88.244:3306/realestate?characterEncoding=utf8&useSSL=false
    ports:
      - "7771:7771"
  user-center:
    image: 192.168.88.244:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/user-center
    command: ["192.168.88.244:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    environment:
      servicecomb_service_registry_address: http://192.168.88.244:30100
    ports:
      - "6877:6877"
