#
## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------

# all interconnected microservices must belong to an application wth the same ID
APPLICATION_ID: houserush
service_description:
  # name of the declaring microservice
  name: house-order
  version: 5.1.23
#  environment: development
servicecomb:
  service:
    registry:
      address: http://192.168.229.184:30100
      instance:
        watch: true
        healthCheck:
          interval: 5

  rest:
    address: 0.0.0.0:6788
  handler:
    chain:
      Provider:
        default: bizkeeper-provider
      #Consumer:
      #  default: tracing-consumer
        #,loadbalance
  tracing:
    collector:
      address: http://192.168.229.184:9411
spring:
  datasource:
    url: jdbc:mysql://192.168.229.184:3306/houserush_order?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      initial-size: 15
      max-wait: 2000
      max-active: 200
      max-idle: 50
      default-auto-commit: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
  redis:
    database: 0
    host: 192.168.229.184
    port: 6379
    #password: 123456
    pool:
      max-active: -1
      max-wait: 30
      max-idle: 30
      min-idle: 5
      timeout: 3000

